development:
  adapter: postgresql
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: rails
  password: rails

test:
  adapter: postgresql
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: rails
  password: rails


production:
  adapter: postgresql
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: rails
  password: rails 


# possible adapters
#  mysql      - MRI, jruby
#  mysql2     - MRI
#  postgresql - MRI
