development:
  adapter: mysql2
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: rails
  password: rails_pwd
  socket: /var/run/mysqld/mysqld.sock
  reconnect: false
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: rails
  password: rails_pwd
  socket: /var/run/mysqld/mysqld.sock
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: rails
  password: rails_pwd


# possible adapters
#  mysql      - MRI
#  jdbcmysql  - jruby
#  mysql2     - MRI
#  postgresql - MRI
