development:
  adapter: postgresql
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: testrails2
  password: sql_pwd_testrails2
 
test:
  adapter: postgresql
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: testrails2
  password: sql_pwd_testrails2
 
production:
  adapter: postgresql
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: testrails2
  password: sql_pwd_testrails2


# possible adapters
#  mysql      - MRI, jruby
#  mysql2     - MRI
#  postgresql - MRI
