development:
  adapter: jdbcmysql
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: rails
  password: ""
  #socket: /var/run/mysqld/mysqld.sock
  #reconnect: false
  #pool: 5

test:
  adapter: jdbcmysql
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: rails
  password: ""
  #socket: /var/run/mysqld/mysqld.sock
  #reconnect: false
  #pool: 5

production:
  adapter: jdbcmysql
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: rails
  password: ""


# possible adapters
#  mysql      - MRI
#  jdbcmysql  - jruby
#  mysql2     - MRI
#  postgresql - MRI


#activerecord-jdbcmysql-adapter
