development: &default
  #adapter: <%= RUBY_PLATFORM =~ /java/ ? 'jdbcmysql' : 'mysql' %>
  #adapter: mysql2
  adapter: pg
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: rails
  password: ""

test:
  #adapter: <%= RUBY_PLATFORM =~ /java/ ? 'jdbcmysql' : 'mysql' %>
  #adapter: mysql2
  adapter: pg
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: rails
  password: ""

production:
  #adapter: <%= RUBY_PLATFORM =~ /java/ ? 'jdbcmysql' : 'mysql' %>
  #adapter: mysql2
  adapter: pg
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: rails
  password: ""
