development:
  adapter: mysql2
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: rails
  password: ""

test:
  adapter: mysql2
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: rails
  password: ""

production:
  adapter: mysql2
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: rails
  password: ""



# possible adapters
#  jdbcmysql - jruby sql
#  mysql     - MRI
#  mysql2    - MRI
#  pg        - MRI
