development:
  adapter: pg
  encoding: utf8
  database: TestRails2_development
  host: localhost
  username: rails
  password:

test:
  adapter: pg
  encoding: utf8
  database: TestRails2_test
  host: localhost
  username: rails
  password:

production:
  adapter: pg
  encoding: utf8
  database: TestRails2_production
  host: localhost
  username: rails
  password: 
