require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ModelDataController do

  # This should return the minimal set of attributes required to create a valid
  # ModelDatum. As you add validations to ModelDatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "boolean1" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ModelDataController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all model_data as @model_data" do
      model_datum = ModelDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:model_data).should eq([model_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested model_datum as @model_datum" do
      model_datum = ModelDatum.create! valid_attributes
      get :show, {:id => model_datum.to_param}, valid_session
      assigns(:model_datum).should eq(model_datum)
    end
  end

  describe "GET new" do
    it "assigns a new model_datum as @model_datum" do
      get :new, {}, valid_session
      assigns(:model_datum).should be_a_new(ModelDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested model_datum as @model_datum" do
      model_datum = ModelDatum.create! valid_attributes
      get :edit, {:id => model_datum.to_param}, valid_session
      assigns(:model_datum).should eq(model_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ModelDatum" do
        expect {
          post :create, {:model_datum => valid_attributes}, valid_session
        }.to change(ModelDatum, :count).by(1)
      end

      it "assigns a newly created model_datum as @model_datum" do
        post :create, {:model_datum => valid_attributes}, valid_session
        assigns(:model_datum).should be_a(ModelDatum)
        assigns(:model_datum).should be_persisted
      end

      it "redirects to the created model_datum" do
        post :create, {:model_datum => valid_attributes}, valid_session
        response.should redirect_to(ModelDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved model_datum as @model_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        ModelDatum.any_instance.stub(:save).and_return(false)
        post :create, {:model_datum => { "boolean1" => "invalid value" }}, valid_session
        assigns(:model_datum).should be_a_new(ModelDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ModelDatum.any_instance.stub(:save).and_return(false)
        post :create, {:model_datum => { "boolean1" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested model_datum" do
        model_datum = ModelDatum.create! valid_attributes
        # Assuming there are no other model_data in the database, this
        # specifies that the ModelDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ModelDatum.any_instance.should_receive(:update_attributes).with({ "boolean1" => "false" })
        put :update, {:id => model_datum.to_param, :model_datum => { "boolean1" => "false" }}, valid_session
      end

      it "assigns the requested model_datum as @model_datum" do
        model_datum = ModelDatum.create! valid_attributes
        put :update, {:id => model_datum.to_param, :model_datum => valid_attributes}, valid_session
        assigns(:model_datum).should eq(model_datum)
      end

      it "redirects to the model_datum" do
        model_datum = ModelDatum.create! valid_attributes
        put :update, {:id => model_datum.to_param, :model_datum => valid_attributes}, valid_session
        response.should redirect_to(model_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the model_datum as @model_datum" do
        model_datum = ModelDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ModelDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => model_datum.to_param, :model_datum => { "boolean1" => "invalid value" }}, valid_session
        assigns(:model_datum).should eq(model_datum)
      end

      it "re-renders the 'edit' template" do
        model_datum = ModelDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ModelDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => model_datum.to_param, :model_datum => { "boolean1" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested model_datum" do
      model_datum = ModelDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => model_datum.to_param}, valid_session
      }.to change(ModelDatum, :count).by(-1)
    end

    it "redirects to the model_data list" do
      model_datum = ModelDatum.create! valid_attributes
      delete :destroy, {:id => model_datum.to_param}, valid_session
      response.should redirect_to(model_data_url)
    end
  end

end
